# This is a basic workflow to help you get started with Actions
name: Label issues
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types:
      - reopened
      - opened
jobs:
  # This workflow contains a single job called "build"
  label_issues:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.2
        with: 
          add-labels: "triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
